apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  progressDeadlineSeconds: 3600
  replicas: 4
  revisionHistoryLimit: 15
  selector:
    matchLabels:
      io.kompose.service: django
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: django
    spec:
      containers:
      - args:
        - /start.sh
        image: maja39/django-demo:0.2
        imagePullPolicy: Always
        name: django
        # Resource allocation
        resources:
          requests:
            cpu: 100m
            memory: 34Mi
          limits:
            cpu: 1
            memory: 200Mi
            # Try crashloop by setting memory to less than 30 Mi
        # Resource allocation end
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
